### ISSUE TITLE
Wrong circle geometry

### ISSUE THREAD

**Issue by parotikov** [gdsestimating/three-dxf#18]
Hi! Thank you for that great library!

I have a problem with this dxf file: http://flowrez.prosto-tak.ru/test.dxf

It must look like http://flowrez.prosto-tak.ru/1.PNG
but its rendering like this: http://flowrez.prosto-tak.ru/2.PNG
i.e. circles not drawing correctly

could you, please, fix this problem?

**Comment by bzuillsmith** [comment]
This appears to be an issue with Splines. All your circles and curves are drawn with Splines for some reason. Splines are a very new feature in Three-dxf. In your case, they are either being parsed incorrectly or some values of the spline are not accounted for when drawing. I'll take a look

**Comment by bzuillsmith** [comment]
Published in 0.3.1. I'm closing for now. If I'm wrong and quadratic splines are the wrong thing to be using in this case, feel free to reopen.

**Comment by bzuillsmith** [comment]
Actually, I'm going to reopen. I'm still learning about splines so bare with my lack of knowledge. Opening the file in a couple other programs I see it is indeed supposed to create nice arcs so apparently I'm not understanding some key part of this.

**Comment by parotikov** [comment]
Program is Rhino.
I'm just developing a microservice that calculates the cost of waterjet (hydro-abrasive) cutting of parts, based on the length of the cut of the drawing. I'm not a creator of this dxf files.
If you want, I can check a few more professional drawings, whether they are displayed correctly

**Comment by bzuillsmith** [comment]
I think what you've given me is fine. I was just unaware of all the different parameters of a spline at first. I've been trying to read up on them and understand them better. Right now I'm getting the impression we can't immediately support the kinds of splines you have but I'm still researching and looking into it. I think you have a [weighted (rational) spline](https://en.wikipedia.org/wiki/Non-uniform_rational_B-spline#Example:_a_circle) and I don't think Three.js (the drawing library we use to draw things) handles weights on the spline as talked about in [this issue](https://github.com/mrdoob/three.js/issues/1799) . Therefore you see more of a quadratic curve instead of an arc of a circle in your drawing. So at the moment, I recommend changing those circles to actual CIRCLE entities and the arcs on the outer edges to actual ARC entities, if you want them to draw properly in three-dxf. But I don't know if your requirements are as simple as that.

**Comment by parotikov** [comment]
Hi!
I found one more strange thing:
When I try to calculate sum of arc length (L = Pi * Radius * AngleLength / 180), I get wrong result.
I found, that in [dxf-parser](https://github.com/gdsestimating/dxf-parser/blob/master/dist/dxf-parser.js#L1378) you transform start and end angle value, so original values are not available to me.
So, I modify your code like this:
![image](https://user-images.githubusercontent.com/4922010/35374351-912fd9a8-01b3-11e8-8a06-a694cb2cf3e4.png)
and now I get correct angles (startAngle2, endAngle2, angleLength2) in dxf-parser output and can calculate arc's length.

**Comment by bzuillsmith** [comment]
Hmmm, yeah, that doesn't look right. I don't believe I ever tested arcs in Three.js. I don't recall why I even made an angleLength. Probably could have just used ArcCurve in Three.js.

In your calculations, you are using degrees (at least that's what the DXF documentation says the values should be in). Three.js expects them in radians which is why I converted them with `Math.PI / 180 * angle`. So I think angleLength can be ignored for the moment and we can simply usce `ArcCurve` in Three.js to draw the curve for us.

**Comment by bzuillsmith** [comment]
I believe it's fixed in df01c98. Let me know if you continue to have problems.
