### ISSUE TITLE
Some of drawings seems different from AutoCAD

### ISSUE THREAD

**Issue by edips** [gdsestimating/three-dxf#24]
Thank you for this great project. It can open big dxf files faster than AutoCAD :) I have a project that it seems different in three-dxf in comparison with AutoCAD like this:
DXF file on three-dxf sample viewer:
![dxf_treejs](https://user-images.githubusercontent.com/3856713/51594483-949b1600-1f05-11e9-83ee-b029cc294d0d.png)
DXF file on AutoCAD:
![autocad](https://user-images.githubusercontent.com/3856713/51594496-9c5aba80-1f05-11e9-84b0-9fce308940ae.png)

Object type of lines are "Block Referance". and some of lines are polylines. Is it because the object type is Block reference?

**Comment by edips** [comment]
I will upload the dxf file tomorrow when I go to office. I saw only a few lines that isn't like the original. Many lines are seen as expected.

**Comment by edips** [comment]
I uploaded DXF data. Thanks.
[Network.zip](https://github.com/gdsestimating/three-dxf/files/2792242/Network.zip)

**Comment by bzuillsmith** [comment]
At first I thought maybe three-dxf was reading the LWPolylines wrong, but now I'm wondering if there is some amount of rounding error because your numbers are huge with many digits past the decimal. I think javascript may be struggling to do the math. I haven't confirmed this, it's just a hunch.

I wonder if normalizing this file a bit so that everything is not in a block would help... or maybe scaling it up and then normalizing? Not sure if this is an option for you.

**Comment by bzuillsmith** [comment]
Still debugging this. I pulled out just a sample from the original file, exploded it, and it drew fine. So the data is being parsed properly. Something about putting blocks in a Three.js group (Object3D) is causing this. It still looks like it could be a precision/rounding issue to me but I'm not totally certain.

**Comment by edips** [comment]
The dxf file is very complex, even AutoCAD opens it in a few minutes. I will export piece of the dxf and will test again. Thank you.

**Comment by bzuillsmith** [comment]
I have asked a question about this on [StackOverflow ](https://stackoverflow.com/questions/54705002/why-are-three-js-geometries-losing-precision-with-large-numbers) and demonstrated the heart of the problem with a [code pen](https://codepen.io/bzuillsmith/pen/OdBgEz). The issue appears to be with Three.js. It just can't handle those big numbers for some reason and so your vertices are getting rounded to positions on top of one another. Hopefully we get some smart people telling us why!

**Comment by bzuillsmith** [comment]
Looks like we got an answer on StackOverflow. In short -- WebGL uses floating point numbers, not doubles. That means all these large values in your vertices are being rounded. The solution would be to adjust your entities in your file to be more centered around the origin (0,0). It might be easier to "explode" the drawing first because every entity in your drawing is in a block which adds to the complexity of getting all these coordinates smaller.

**Comment by Serthys** [comment]
Maybe it would be a good idea to add a warning when it's parsing big or small numbers that doesn't fit in a float.

**Comment by edips** [comment]
Thank you for your time. Yes blocks makes it very complex to be displayed. Even AutoCAD is freezing, ArcGİS sometimes stops working when I important the complex dxf. I think my data's blocks are generated by a script. Three-dxf opens and displays it very faster.
As I tested Three-dxf displays preciously for other dxf files that doesn't contain blocks. WebGL's rounding may be due to increase the performance. 
I am new to JavaScript and nodejs. I hope to discover it by the time :)

**Comment by edips** [comment]
@Serthys I think it would be good idea to add unit dialog that the workspace's unit can be adjusted with meter/millimeter or imperial metrics. İf the default unit is meter for workspace, it may be a problem for complex drawings that the unit is millimeter. WebGL might convert and round the decimal of millimeter to meter so the vertices might be wrong. But if the project's default units can be set, the rounding issue can minimized.

**Comment by bzuillsmith** [comment]
Three-dxf is a rather simple viewer and doesn't really get into modifying the workspace or the data at all. Changing the units would need to be done in something like AutoCAD for via custom javascript code before the drawing data is handed to three-dxf.

Also, the problem isn't blocks directly. Rather, it's the large values for your vertices. Your data is at coordinates like x = 3,000,000.12345 and y = 4,000,000.123456 and is beyond what computers can store in a 32-bit floating point number (autocad and other programs typically use 64-bit floating point numbers). If they were in blocks but were using smaller numbers, it would all work fine. However, because they are in blocks, it will be harder to process all the entities and translate their coordinates so that they are smaller. Exploding will move everything out of blocks, but you will lose your attribute data that labels everything so it's probably only something you would want to do for display purposes.

**Comment by edips** [comment]
Yes its coordinate system is cartesian X and Y (like UTM). I will try to convert the project's coordinate system to WGS84 (latitude, longitude). I will report here after testing.

**Comment by edips** [comment]
I would test piece of the dxf file but I get text files instead of canvas. I use tried it on Manjaro/Virtualbox. I tried the project successfully on another Laptop which it was Windows 10, I installed npm to Ubuntu for Win10.

![screenshot_2019-03-02_02-54-28](https://user-images.githubusercontent.com/3856713/53673205-38ab7600-3c97-11e9-8302-13867683402e.png)

**Comment by bzuillsmith** [comment]
You'll want to use the developer tools in your browser to see if there were any JavaScript errors. My guess is it had an error while generating the drawing.
