### ISSUE TITLE
Can not run Sample properly

### ISSUE THREAD

**Issue by yinxuan1128** [gdsestimating/three-dxf#29]
I follow the Run Samples step by step
But when I open http://127.0.0.1/sample,I got the error response like below:
ERR_TOO_MANY_REDIRECTS
and the browser's address change to http://127.0.0.1:8080/sample///////////////////
I don know why.

**Comment by shivkoirala** [comment]
> I follow the Run Samples step by step
> But when I open http://127.0.0.1/sample,I got the error response like below:
> ERR_TOO_MANY_REDIRECTS
> and the browser's address change to http://127.0.0.1:8080/sample///////////////////
> I don know why.

Any idea how this was closed.

**Comment by Serthys** [comment]
He closed the issue 5 minutes after opening it so maybe he just made a mistake in the setup.

**Comment by natmaiden** [comment]
I am getting the exact same error when trying to run the sample. any idea on how to fix that!?

**Comment by Serthys** [comment]
@natmaiden Looks like the issue is coming from a http-server dependency problem.
[Here's the http-server issue with a workarround](https://github.com/http-party/http-server/issues/525#issuecomment-493210930).
I was tinkering with it and noticed that if you access http://127.0.0.1:8080/sample/index.html instead of http://127.0.0.1:8080/sample it load correctly so there's also that.

**Comment by Serthys** [comment]
@gdsestimating Maybe the http-server@0.9.0 should be a added as a devDependency otherwise the working example on the README would depend on an unknown version.
