### ISSUE TITLE
Import DXF, missing text and filler missing

### ISSUE THREAD

**Issue by David-C-gd-y** [gdsestimating/three-dxf#41]
Import DXF, missing text and filler missing

**Comment by David-C-gd-y** [comment]
[Drawing1.zip](https://github.com/gdsestimating/three-dxf/files/4243090/Drawing1.zip)

**Comment by Serthys** [comment]
If you check the console there are logs mentioning your problem.
> Can't render this multipline MTEXT entity, sorry.

According to the README MText is not supported. If you see where the log is used there's a comment explaining why:
https://github.com/gdsestimating/three-dxf/blob/78657c8d6bf9b9124ffe3216da1e370a842e1d4e/src/index.js#L268-L271

If it first your use case you can transform the MText to regular text using you DXF editor of choice before importing it on three-dxf.

**Comment by wzjgzcc** [comment]
First of all, thank you. I have another question. After it is converted into regular text, the text will be displayed as a question mark
[NoNoHatchMtext.zip](https://github.com/gdsestimating/three-dxf/files/4265220/NoNoHatchMtext.zip)

**Comment by bzuillsmith** [comment]
We are nearing some support for MText. I've experimenting with a library called [troika-three-text](https://github.com/protectwise/troika/tree/master/packages/troika-three-text) that handles it multiline text pretty well. I've made a [branch of the same name in three-dxf](https://github.com/gdsestimating/three-dxf/tree/troika-three-text) to work on it. The alignment doesn't work 100% and I just posted [an issue](https://github.com/protectwise/troika/issues/160) discussing a possible remedy with that library. Otherwise I'll have to calculate some offsets to position the text properly.

**Comment by bzuillsmith** [comment]
Multiline MText is now supported in 1.3 with some limitations in formatting:

* the font is not dynamic.
* stacked fractions, changes in font-size, and other kinds of formatting changes are within the same entity are not supported
